# -*- coding: utf-8 -*-
"""Assignment_Housing_Agency__Boston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KdqRbchKpxLd9AXV_2UZAS7OiDfVhjk

## Assignment - Statistics for Data Science with Python

### Load Dataset
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats
import statsmodels.api as sm

boston_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ST0151EN-SkillsNetwork/labs/boston_housing.csv'
boston_df = pd.read_csv(boston_url)

boston_df.describe()

boston_df.head(10)

"""### Become familiar with the dataset
The following describes the dataset variables:

·      CRIM - per capita crime rate by town

·      ZN - proportion of residential land zoned for lots over 25,000 sq.ft.

·      INDUS - proportion of non-retail business acres per town.

·      CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)

·      NOX - nitric oxides concentration (parts per 10 million)

·      RM - average number of rooms per dwelling

·      AGE - proportion of owner-occupied units built prior to 1940

·      DIS - weighted distances to five Boston employment centres

·      RAD - index of accessibility to radial highways

·      TAX - full-value property-tax rate per $10,000

·      PTRATIO - pupil-teacher ratio by town

·      LSTAT - % lower status of the population

·      MEDV - Median value of owner-occupied homes in $1000's

### Generate Descriptive Statistics and Visualizations
#### Question 1: For the 'Median value of owner-occupied homes' provide a boxplot

Evalution : This question carries 10 marks
"""

# Solution goes here:
#taking boxplot using column MEDV
boston_df.boxplot(column=['MEDV'])
#print title of boxplot
plt.title("Median Values of Owner-occupied homes")
#show boxplot of MEDV
plt.show()

"""#### Question 2: Provide a histogram for the Charles River variable

Evalution : This question carries 20 marks
"""

# Solution goes here:
#taking histogram catplot and x axis varial is CHAR and y axis there count is display
sns.catplot(x='CHAS', kind='count', data=boston_df)
#taking label of x axis
plt.xlabel("Charles River Variable")
#show histogram
plt.show()

"""#### Question 3: Provide a boxplot for the MEDV variable vs the AGE variable - Discretize the age variable into three groups of 35 years and younger, between 35 and 50 years and older

Evalution : This question carries 20 marks
"""

# Solution goes here:
#Taking condition of age of 35 and younger
boston_df.loc[(boston_df.AGE <= 35), 'age_group']
#Taking condition of Year between 35 and 50.
boston_df.loc[((boston_df.AGE > 35)&(boston_df.AGE <= 50)), 'age_group']
#Taking condition of older
boston_df.loc[(boston_df.AGE > 50), 'age_group']
#Taking x and y axis variable
ax = sns.boxplot(x='age_group', y='MEDV', data=boston_df)
#print title of the graph
plt.title("Median value vs Age Groups")
plt.ylabel("Median Value")
#show this graph
plt.show()

"""#### Question 4: Provide a scatter plot to show the relationship between Nitric oxide concentrations and the proportion of non-retail business acres per town. What can you say about the relationship?

Evalution : This question carries 20 marks
"""

# Solution goes here:
#Taking scatterplot y axis of indus and x axis of nox
ax = sns.scatterplot(y='INDUS', x='NOX', data=boston_df)
#print x label
plt.xlabel("concentration of Nitric Oxide-ppm")
#print y label
plt.ylabel("proportion of non-retail Business acres")
#show this graph
plt.show()

"""#### Question 5: Create a histogram for the pupil to teacher ratio variable.

Evalution : This question carries 20 marks
"""

# Solution goes here:
#Taking histogram y axis of PTRATIO
sns.catplot(y="PTRATIO", kind="count", data=boston_df)
#Taking y axis label
plt.ylabel("pupil to teacher ration");
#show this graph
plt.show()

"""#### Question 6: Can we conclude that there is no relationship between Nitric oxide concentrations and proportion of non-retail business acres per town? (Pearson Correlation)

Evalution : This question carries 10 marks
"""

# Solution goes here:
# Null Hypothesis is no relationship between Nitric Oxide concentration and proportion of non-retail business acres per town.
# Alternative Hypothesis is a relationship between Nitric Oxide concentration and proportion of non-retail business acres per town.
scipy.stats.pearsonr(boston_df.NOX, boston_df.INDUS)

#there is p-value is greter than 0.05 so reject the null hypothesis.

